### ISSUE TITLE
api is pointing to production while in dev

### ISSUE THREAD

**Issue by CknDev** [nicklaw5/stryve#42]
I cannot make stryve client application point to my local api 

Scenario:
----

Fresh install following the wiki 'get-started' instructions 
Run servers, spawn the browser application
Register a new account
Login with the account just created
Open dev tools
See that the api points to api.stryve.io instead of localhost:8181

----

I double checked stryve-client-api, the baseURL is https://localhost:8181
No records in my db for users table

**Comment by nicklaw5** [comment]
Hmmm, I thought https://github.com/nicklaw5/stryve-api-client/blob/master/lib/api.js#L8 may have been the issue. Will look into this when I get home from work.

**Comment by CknDev** [comment]
found it, `stryve-app/node_modules/stryve-api-client` still have `baseUrl ` pointing to `api.stryve.io`

**Comment by nicklaw5** [comment]
Ahh I need to republish the npm package or have it also pull direcly from the Github whilst still in heavy development. Thoughts?

**Comment by CknDev** [comment]
since it's published, it's a bit odd to use the github 
I would republish, then pass under github time i write tests (so not blocking for new features) then pass back into published version once tests are done

**Comment by nicklaw5** [comment]
Ok. Another alternative is to merge nicklaw5/stryve-api-client together with nicklaw5/stryve?

**Comment by CknDev** [comment]
i like it separated, more maintainable, but your call

**Comment by nicklaw5** [comment]
Fixed this with stryve-api-client@0.1.2

Run `npm update`
