### ISSUE TITLE
unable to submit request to api server over localhost

### ISSUE THREAD

**Issue by nicklaw5** [nicklaw5/stryve#44]
When attempting to submit api requests from the socket.io server, the below error is thrown:

```bash
$ npm run server-dev

> stryve@0.3.0-alpha server-dev F:\Code\stryve
> SET PROD_ENV=0 & node src/server.js


Listening on *:3333

User connected and ready.
A user has connected to the server.
{ [Error: connect ECONNREFUSED 127.0.0.1:8181]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8181 }
{ errorCode: 0,
  errorMessage: 'connect ECONNREFUSED 127.0.0.1:8181' }
```

**Comment by nicklaw5** [comment]
Can do this:
```bash
$ curl http://localhost:8181/  # Returns successful response
```
but if I replace `localhost` with `127.0.01` it fails:
```bash
$ curl http://127.0.0.1:8181/  # Failed to connect to 127.0.0.1 port 8181: Connection refused
```

**Comment by nicklaw5** [comment]
In addition to my previous post, although `localhost` [is explicitly listed in the code](https://github.com/nicklaw5/stryve-api-client/blob/master/lib/api.js#L8), it seem node translates the hostname to an IP address.

**Comment by CknDev** [comment]
I don't get a refused connection when requesting 127.0.0.1:8181 (linux)

**Comment by nicklaw5** [comment]
@CknDev 
May be my local dev environment that is screwing with something
Are you able to run everything without error using the Getting Started guide?
I have remove node-webkit as a dependency, it must now be installed globally. Updated the readme and Getting Started tutorial with respect to this change.

**Comment by CknDev** [comment]
Made a fresh install with upstream (apart from the db step (1)); 
Everything is running (register; login; create server; create channel; send message)

**Comment by nicklaw5** [comment]
looks to be an issue just with my dev environment. closing for now.
