### ISSUE TITLE
Self Hosted Servers?

### ISSUE THREAD

**Issue by daveb778** [nicklaw5/stryve#64]
Sorry, for opening another ticket. But i would also like to know if there's any plans to allow users to host their own servers?

**Comment by nicklaw5** [comment]
Yes, self hosted servers are one of the key features of this application. I'm planning on including an [Ansible](http://docs.ansible.com/ansible/index.html) playbook for deploying to a server in a matter of minutes.

By the way, I have began re-writing this app from the ground up and is now hosted over [here](https://github.com/stryveapp/)

**Comment by daveb778** [comment]
Ahh i see, also thanks for the replies.
