### ISSUE TITLE
Cannot access

### ISSUE THREAD

**Issue by roccosette** [nicklaw5/stryve#65]
Hi,

My node is launched :
netstat -paunt |grep 8080
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      5213/node

But i can not access to the website :
telnet serveur 8080
Trying 192.168.1.10...
telnet: Unable to connect to remote host: Connection refused

Can you help ?

**Comment by nicklaw5** [comment]
I ran into this issue myself a while back. Take a look at [this post](https://laracasts.com/discuss/channels/general-discussion/connect-econnrefused-1270018181) and see if it can help in your situation.

**Comment by roccosette** [comment]
Hi,

When i made this command curl i get that :
/home/rsette/ curl http://localhost:8080
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Stryve</title>
  </head>
  <body>

  	<app></app>

    <script src="dist/build.js"></script>
  </body>
</html>

But i can't go to localhost i think, but my ports 8080 are open.

**Comment by nicklaw5** [comment]
What happens if you replace `localhost` with `127.0.0.1`?

**Comment by roccosette** [comment]
```
`/opt/stryve/ curl http://127.0.0.1:8080
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Stryve</title>
  </head>
  <body>

  	<app></app>

    <script src="dist/build.js"></script>
  </body>
</html>`
```

curl http://192.168.1.10:8080
curl: (7) Failed to connect to 192.168.1.10 port 8080: Connexion refusée

**Comment by nicklaw5** [comment]
What command are you running to start the API (Laravel) server?

**Comment by roccosette** [comment]
You want speak about :
npm run dev-server ?

**Comment by nicklaw5** [comment]
The node server is not your typical HTTP server, it's a websocket server that handles the sending of messages between channels. You need to also run an API server alongside it. See the getting [started guide](https://github.com/nicklaw5/stryve/wiki/Getting-Started).

**Comment by roccosette** [comment]
I'm trying and i searching on web but i don't find solution for this :
/opt/stryve-api-php/ php artisan migrate:refresh --seed

  [PDOException]                                                               
  SQLSTATE[HY000] [1130] Host 'serveur' is not allowed to connect to this Mar  
  iaDB server

**Comment by nicklaw5** [comment]
Do you have MariaDB running? Have you created a database, as well as a username and password for connecting to the DB? If so, have you updated your `.env` file to reflect the DB connection settings?

If you've done all that, can you connect to the DB manually. For example:

```
$ mysql -u <username> -p
```

**Comment by roccosette** [comment]
/home/git/ mysql -u stryve_user -p
Enter password: 

MariaDB [(none)]> use stryvedb;
Database changed

/opt/stryve-api-php/ cat .env
APP_ENV=local
APP_DEBUG=false
APP_KEY=KEY

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=stryvedb
DB_USERNAME=stryve_user
DB_PASSWORD=PASSWORD

/opt/stryve-api-php/ php artisan migrate:refresh --seed

                                                                               
  [PDOException]                                                               
  SQLSTATE[HY000] [1130] Host 'serveur' is not allowed to connect to this Mar  
  iaDB server

**Comment by roccosette** [comment]
How to change host choose for connect ?

**Comment by roccosette** [comment]
I found, wait for next

**Comment by roccosette** [comment]
/opt/stryve-api-php/ php artisan serve --port=8181
Laravel development server started on http://localhost:8181/

netstat -paunt | grep 8081
no result

**Comment by nicklaw5** [comment]
I'm not sure of your network configuration so it is difficult for me to provide any sort of remedy to the issues you are having. Perhaps try starting the server with the following host:

```
$ php artisan serve --host=0.0.0.0 --port=8181
```

**Comment by roccosette** [comment]
Nothing change, i think php artisan make nothing, no port open see with netstat...

**Comment by roccosette** [comment]
Finally it's an iptables problem, but only your command works, not the first.
But now i get "Sorry, the page you are looking for could not be found.", i search...

**Comment by nicklaw5** [comment]
The PHP server is not the app. Once you have the API running, in the `stryve` repo you need to run `npm run w-app` then open http://localhost:8080 in your browser.

**Comment by roccosette** [comment]
But i have always this error when i try to make telnet.

telnet localhost 8080
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.

telnet 192.168.1.10 8080
Trying 192.168.1.10...
telnet: Unable to connect to remote host: Connection refused

iptables open

**Comment by nicklaw5** [comment]
I don't know what issue you're having. I have managed to get everything running just now by following the steps in the [getting started guide](https://github.com/nicklaw5/stryve/wiki/Getting-Started). Beyond that, I can't help.

**Comment by roccosette** [comment]
Can i change host launch with npm ?

**Comment by nicklaw5** [comment]
See https://stackoverflow.com/questions/29412303/how-to-bind-http-server-with-express-object-to-a-specific-ip-address

And you'll need to make the [change on this line](https://github.com/nicklaw5/stryve/blob/master/src/server.js#L15).

**Comment by nicklaw5** [comment]
@roccosette How did you go? Did you get it running?

**Comment by nicklaw5** [comment]
Closing for now. Please re-open if you are still having issues.
